name: API Testing
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies and Playwright Browsers
        run: |
          cd api-testing
          npm ci
          npx playwright install --with-deps
      - name: Run API Tests
        run: |
          cd api-testing
          npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: api-testing/playwright-report/
          retention-days: 30
