name: Playwright Testing
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies and Playwright Browsers
        run: |
          cd playwright-assignment
          npm ci
          npx playwright install --with-deps

      - name: Run Visual Tests - Create Baseline Snapshots
        continue-on-error: true
        run: |
          cd playwright-assignment
          npx playwright test specs/visual-tests/ --update-snapshots

      - name: Run Visual Tests - Run Against Baseline Snapshots
        continue-on-error: true
        run: |
          cd playwright-assignment
          npx playwright test specs/visual-tests/

      - name: Run Assignment 01 - Playwright Scripts
        continue-on-error: true
        run: |
          cd playwright-assignment
          npx playwright test specs/playwright-advanced-assignment/

      - name: Upload Visual Test Snapshots
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: visual-test-snapshots
          path: |
            playwright-assignment/visual-tests/**-snapshots/
          retention-days: 10

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-assignment/playwright-report/
          retention-days: 10
